# Generated by Django 2.1.3 on 2018-11-12 15:13

from django.db import migrations

from accounts.models import AccountUser


def create_default_user(apps, schema_editor):
    usr = AccountUser(
        username='ad',
        is_staff=True,
        is_superuser=True,
    )
    usr.set_password('Adm123')
    usr.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_default_user,
            lambda x, y: (x, y)
        )
    ]