<<<<<<< HEAD
# Generated by Django 2.1.2 on 2018-11-09 16:36
=======
# Generated by Django 2.1.3 on 2018-11-10 17:02
>>>>>>> 070b20a43dd7b4b011c26b3d783235212c88555d

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('value', models.ImageField(upload_to='images')),
            ],
        ),
    ]
